naver/ngrinder

- ngrinder-controller/src/test/java/org/ngrinder/operation/MockScriptConsoleController.java
- ngrinder-controller/src/test/java/org/ngrinder/operation/ScriptConsoleControllerTest.java
ScriptConsoleController의 run메소드에서 UserContext를 사용하도록 수정되어
UserContext를 autowired할 수 있도록 수정하였습니다.
> #58 NullPointerException in ScriptConsoleControllerTest

- release_note.txt
In the release note, 3.3.1 version release data is mistakenly noted as 3.31. I changed it to the official planned date.
> modify 3.3.1 planned release date

- docker/multi/multi-agent/scripts/run.sh
- docker/standalone/agent/scripts/run.sh
I have enhanced agent starting performance.
- deleting pid before starting the agent
- downloading the agent binary from the controller only when it doesn't exist. 
It supports "docker start" and "docker stop" scheme.
> modified agent binary download logic

- docker/standalone/agent/.gitignore
- docker/standalone/agent/Dockerfile
- docker/standalone/agent/README
- docker/standalone/agent/scripts/run.sh
Use built in controller if the CONTROLLER_ADDR is not provided.
The basic usage is like below
docker run -it ngrinder/agent:3.3-p2 [agent execution arguments]
> add builtin agent

- .travis.yml
Travis is execute to the 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V' for build by default.
So we just need add script that skip test script instead to default test script.
> #114 make the travis skip the test

- ngrinder-starter/src/main/java/org/ngrinder/NGrinderControllerStarter.java
recover jetty timeout settings to reduce unnecessary timeout log
> #137 fix hibernate warning

- ngrinder-core/src/main/java/net/grinder/SingleConsole.java
The hardcoded comma separator has been replaced with the dynamic one.
referred to #234
> Fix csv separator inside SingleConsole

- ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/basic_report.ftl
- ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
- ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl
Remove context path from url parameter when creating AjaxObj
This problem causes the duplicated context path when running nGrinder under a specific context path.
This problem was issued by @lingsoul. Thx.
> Remove context path from  AjaxObj url

- ngrinder-controller/src/main/java/org/ngrinder/common/constant/ControllerConstants.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-controller/src/main/java/org/ngrinder/script/service/ScriptValidationService.java
- ngrinder-controller/src/main/resources/controller-properties.map
- ngrinder-controller/src/main/resources/ngrinder_home_template/system.conf
- ngrinder-controller/src/test/java/org/ngrinder/script/service/ScriptValidationServiceTest.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/LocalScriptTestDriveService.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/PropertyBuilder.java
- ngrinder-core/src/main/java/org/ngrinder/common/constants/GrinderConstants.java
- ngrinder-core/src/test/java/net/grinder/engine/agent/PropertyBuilderTest.java
- ngrinder-runtime/src/main/java/org/ngrinder/sm/NGrinderLightSecurityManager.java
To distinguish nGrinder's security level I add NGrinderLightSecurityManager which less secured than NGrinderSecurityManager.
This allows followings.(not allowed in NGrinderSecurityManager.)
**1. multicast
2. tcp connection unspecified address**
If you want to use this, set 'controller.security.level=light'. It only works if controller.security is true.
The default value for this configuration is 'controller.security.level=normal'.
(using NGrinderSecurityManager.)
> Add system configuration for setting security level

- .travis.yml
JDK7 is quite old so we might not  need to build against JDK7.
I removed it out.
> Remove JDK7 build in travis

- .travis.yml
Changed jdk from oraclejdk to openjdk. Because openjdk is more common than oraclejdk.
> Changed jdk from oraclejdk to openjdk in travis

- ngrinder-groovy/src/test/java/net/grinder/scriptengine/groovy/GrinderRunnerTest.java
Ignore GrinderRunnerTest test because it's for input for our Groovy test runner not actual test.
> Fix test failure in GrinderRunnerTest

- pom.xml
Use java 1.7 for minimum running JDK env.
Drop java 1.6 which released 2006. I think it's time to drop it.
> Use java1.7 for minimum running env

- ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java
- ngrinder-controller/src/main/java/org/ngrinder/common/util/SpringSecurityUtils.java
- ngrinder-controller/src/main/webapp/WEB-INF/ftl/agent/list.ftl
- ngrinder-controller/src/main/webapp/WEB-INF/ftl/common/navigator.ftl
- ngrinder-controller/src/test/java/org/ngrinder/agent/controller/AgentManagerControllerTest.java
#304 
Users can view the list of public and User's agents from the agent management menu.
(This menu previously only supported for admin.)
They can only view the following information about the agents.
> Provide limited agent management menu for user permission

- ngrinder-controller/src/test/java/org/ngrinder/agent/service/ClusteredAgentManagerServiceTest.java
I removed test `ClusteredAgentManagerServiceTest.testOther` because the test is meaningless and affects other test.
> Remove unnessesary test

- ngrinder-core/src/main/java/net/grinder/engine/agent/PropertyBuilder.java
Java `System.getProperty ("user.dir")` return the link value when current execution location is a symbolic link. so `workDirectory` value in security manager is different from what i expected.
This commit passes ```ngrinder.base.path``` to test process as a system property. So the path resolution  in security manager can handle the file access well.
> Pass working directory to test process to avoid wrong ngrinder home path on symbolic lynk

- ngrinder-controller/src/test/java/org/ngrinder/agent/service/ClusteredAgentManagerServiceTest.java
Ignored `ClusteredAgentManagerServiceTest` from our tests.
I think this test has a ordering or timing problem each tests.
Issue is low priority than others, so i will deal with later.
> Ignore problematic test class

- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
- ngrinder-core/src/main/java/org/ngrinder/common/constants/AgentConstants.java
- ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
- ngrinder-core/src/main/resources/agent-properties.map
- ngrinder-core/src/main/resources/agent.conf
Add `agent.enable_security` configuration to `agent_conf`.
It is used to operate regardless of the `controller.security` configuration of the controller.
when `agent.enable_security=false` the agent always runs in unsecurity mode.
default value is true.(It depends on controller security configuration.)
> Provide the way to turn off security mode in agent config.

- ngrinder-controller/src/main/java/org/ngrinder/common/constant/WebConstants.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
- ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
When security mode is enabled but its level is light, the target host field in perftest config is not mandatory.
> Make the target host field mandatory only in normal security level

- ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
- ngrinder-core/src/main/java/net/grinder/engine/agent/LocalScriptTestDriveService.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/PropertyBuilder.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/ValidationPropertyBuilder.java
- ngrinder-groovy/src/main/java/net/grinder/script/GTest.java
Fix for #334 
This PR introduces ngrinder.context system property to determine the current context (junit or ngrinder)
Only when ngrinder.context property is given, gtest instruments the code so that the debugging  will be enabled.
> Make gtest only instrument method in ngrinder context

- ngrinder-controller/pom.xml
- ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
- ngrinder-core/pom.xml
- ngrinder-groovy/pom.xml
- ngrinder-runtime/pom.xml
- ngrinder-sh/pom.xml
- ngrinder-starter/pom.xml
- pom.xml
Since nGrinder 3.4.2 has been released, update version as 3.5.0-SNAPSHOT.
> Prepare 3.5.0

- ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentManagerService.java
When agent configuration `region` is empty such as `region=` NPE occurs in `getReadyAgentCount`.
Therefore, use `StringUtils.equals` to compare strings.
> Add defence code for NPE when get ready agent count

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Database.java
- ngrinder-controller/src/main/resources/ngrinder_home_template/database.conf
When user selects mysql as their database, Automatically set character encoding to utf-8.
> Add character encoding option in mysql connection string

- ngrinder-controller/src/main/java/org/ngrinder/infra/init/DBInit.java
- ngrinder-core/src/main/java/org/ngrinder/common/util/ReflectionUtils.java
- ngrinder-core/src/main/java/org/ngrinder/model/BaseEntity.java
- ngrinder-core/src/test/java/org/ngrinder/common/util/ReflectionUtilTest.java
1. Add last modified date and user when init user table.
2. Fixed bug where parent fields could not be merged before saving.
- `getClass().getDeclaredFields()` could not resolve parent fields.
> Fixed bug where parent fields could not be merged before saving.

- ngrinder-controller/src/main/java/org/ngrinder/error/controller/DefaultErrorController.java
Disable default whitelabel error page supported by springboot and add custom error controller.
> Add custom error controller

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
Disable hazelcast all join mechanism when run with non-cluster mode.
`2019-02-20 17:55:53,948 WARN  StandardLoggerFactory.java:49  [dev] [3.11.1] No join method is enabled! Starting standalone.`
> Disable hazelcast all join method when run with non-cluster mode

- ngrinder-controller/src/main/java/org/ngrinder/starter/NGrinderControllerStarter.java
Since bump up spring boot version. 
property key for the context path has been changed.
> Fix deprecated context path property key

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
Sometimes when running controller with cluster mode, hazelcast split brain syndrome was occurred.
so i apply lastet update merge policy to resolve it.
> Apply lastet update merge policy to hazelcast map configuration

- ngrinder-controller/src/main/java/org/ngrinder/user/service/UserService.java
Currently in switch user mode.
hibernate `Lazyinitializationexception` occurs at below line when `userService.getOne()` return cached user object.
https://github.com/naver/ngrinder/blob/develop/ngrinder-controller/src/main/java/org/ngrinder/infra/spring/UserHandlerMethodArgumentResolver.java#L99
so, i fix to use `getOneWithFollowers`.
> Cache user with followers for avoid hibernate lazyinitialization exception

- ngrinder-frontend/src/js/components/common/CodeMirror.vue
Codemirror default line separator is `\n`.
so, `changed()` in `Editor.vue` is aways true in `windows (\r\n)`
https://github.com/naver/ngrinder/blob/feature/convert-to-vuejs/ngrinder-frontend/src/js/components/script/Editor.vue#L280
to solve this, set codemirror line separator depending on OS.
> Set line separator on codemirror depending on OS

- ngrinder-runtime/src/main/java/org/ngrinder/sm/NGrinderSecurityManager.java
[Merge into `master`]
Allow log file deletion in ngrinder secure mode.
Currently, `logback` isn't rolling test logs in secure mode.
> Allow log file deletion in security mode

- ngrinder-controller/pom.xml
- ngrinder-controller/src/main/webapp/WEB-INF/ftl/script/editor.ftl
* Resolve #389 issue.
* New version of lucy xss servlet filter works fine with context path.
* Script editor shows unescaped html (#385)
> Enable saving scripts when running ngrinder-controller with context path

- ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentPackageService.java
- ngrinder-controller/src/main/java/org/ngrinder/common/model/Home.java
- ngrinder-controller/src/main/java/org/ngrinder/common/util/EncodingUtils.java
- ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryController.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/LocalScriptTestDriveService.java
- ngrinder-core/src/main/java/net/grinder/util/AbstractGrinderClassPathProcessor.java
- ngrinder-core/src/main/java/org/ngrinder/common/util/EncodingUtils.java
- ngrinder-core/src/main/java/org/ngrinder/infra/ArchLoaderInit.java
#446
File couldn't be found if there were certain characters in the path when getting the file name from `URL` object (from a URLClassLoader). so apply URL decoding to file name.
> Apply URL decoding when getting file name from URLClassLoader

- docker/agent/Dockerfile
- docker/controller/Dockerfile
Hello,
The use of COPY is preferred over ADD when additional functionalities of ADD are not being used (like spraying the contents of a tar in a folder).
Ref: https://docs.docker.com/engine/articles/dockerfile_best-practices/#add-or-copy
Thanks.
> Use COPY instead of ADD in Dockerfile

- ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java
- ngrinder-controller/src/main/java/org/ngrinder/common/controller/GlobalControllerAdvice.java
- ngrinder-controller/src/main/java/org/ngrinder/common/controller/annotation/GlobalControllerModel.java
- ngrinder-controller/src/main/java/org/ngrinder/home/controller/HealthCheckApiController.java
- ngrinder-controller/src/main/java/org/ngrinder/home/controller/HomeController.java
- ngrinder-controller/src/main/java/org/ngrinder/operation/cotroller/AnnouncementController.java
- ngrinder-controller/src/main/java/org/ngrinder/operation/cotroller/ScriptConsoleController.java
- ngrinder-controller/src/main/java/org/ngrinder/operation/cotroller/SystemConfigController.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
- ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryController.java
- ngrinder-controller/src/main/java/org/ngrinder/user/controller/UserController.java
- ngrinder-controller/src/test/java/org/ngrinder/home/controller/HomeControllerTest.java
Make `GlobalControllerAdvice` work only on controller that return view (app.html)
> exclude api-controller, download controller
> Exclude global attributes settings to api-controller

- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
Currently, command line options for perftest process in the agent is logged only in ${agentName}-${agentNumber}.log file.  
Fix this to ${agentName}-0.log to be sent to controller.
> Fix log file name for agent command line

- ngrinder-frontend/src/js/components/Base.vue
- ngrinder-frontend/src/js/components/common/mixin/PopoverMixin.vue
- ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
- ngrinder-frontend/src/js/components/perftest/list/List.vue
If test have many distribution files, It couldn't view the popover contents and make flickering.
Apply scroll to popover contents.
(popover alive while being hovered)
> Apply scroll to popover contents

- ngrinder-frontend/src/js/components/perftest/detail/Report.vue
If old chart data exist in `{ngrinder-home}/perftest/{user}/{test-id}/report`
Intermittently,  `Report.vue` is rendered old chart.
because, it read old data in created hook before they are deleted.
so, remove problematic hook, chart data is [already handled by bootstrap tab event](https://github.com/naver/ngrinder/blob/develop/ngrinder-frontend/src/js/components/perftest/detail/Detail.vue#L307)
> Remove unnecessary vue hook

- build.gradle
Add gradle task for publishing ngrinder artifact.
For testing, I deployed the artifact that published with gradle to [`ngrinder.maven.repo.test`](https://github.com/naver/ngrinder/tree/ngrinder.maven.repo.test/releases/org/ngrinder/ngrinder-core/3.5.0) branch.
> Add maven publishing task to gradle

- ngrinder-frontend/src/js/components/Base.vue
- ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
Adjust some css
1. Show popover scroll only when needed.
2. Prevent `SmallChart.vue`'s table style affect other components table style.
> Beautify css

- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-controller/src/main/resources/ngrinder_agent_home_template/agent_agent.conf
- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/LocalScriptTestDriveService.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/PropertyBuilder.java
- ngrinder-core/src/main/java/org/ngrinder/common/constants/AgentConstants.java
- ngrinder-core/src/main/java/org/ngrinder/common/constants/GrinderConstants.java
- ngrinder-core/src/main/resources/agent-properties.map
- ngrinder-core/src/main/resources/agent.conf
Support custom JVM classpath for test.
1. Use `grinder.properties`
> This feature not working in `security mode`
2. Use `agent.conf`
> Support custom JVM classpath for test

- ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestApiController.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-core/src/main/java/net/grinder/SingleConsole.java
- ngrinder-frontend/src/js/components/common/mixin/ChartMixin.vue
- ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
- ngrinder-frontend/src/js/components/perftest/report/menu/PerfTest.vue
Support multi user defined data type.
```
// sample
grinder.statistics.registerSummaryExpression("User_defined", "(/ userLong0(+ (count timedTests)))")
grinder.statistics.registerSummaryExpression("User_defined_Error_Count", "(/ userLong1(+ (count timedTests)))")
grinder.statistics.registerSummaryExpression("User_defined_Long_Field", "(/ userLong2(+ (count timedTests)))")
test1 = new GTest(1, "Test1")
test2 = new GTest(2, "Test2")
test3 = new GTest(3, "Test3")
```
> Support multi user defined data type

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
- ngrinder-core/src/main/java/net/grinder/console/communication/AgentProcessControlImplementation.java
- fix hazelcast map config
- fix timer thread not to be shutdown
> Prevent zombie agents from remaining in distributed cache

- ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
- ngrinder-frontend/src/js/components/perftest/report/menu/PerfTest.vue
Make chart duration show correctly.
1. before
2. after
> Make chart duration show correctly

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
- fix size config works fine on non-clustered mode
- simplify hazelcast map configuration
> Improve hazelcast configuration

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
- dist map entries for agent, sampling, monitor must not be cached.
- fix not to use near cache, just use dist map as shared map
> Fix hazelcast config not to use near cache on dist map

- ngrinder-frontend/src/js/components/perftest/report/DetailReport.vue
`Targethost` value may be `{hostname}:{ip}` format so, split that to pass only ip.
> Make monitor chart to be draw correctly

- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
If test finish before ignore sampling count is reached, sampling model will be null.
so i handle this case.
Before
After
> Settings for reproduction of ploblem.
> Handle case of no sampling model

- ngrinder-core/src/main/java/org/ngrinder/NGrinderAgentStarterParam.java
- ngrinder-core/src/main/java/org/ngrinder/common/constants/CommonConstants.java
- ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
1. If `__agent.conf` exists, it is always overwritten & delete.
2. Remove `agent -o option`.
> Remove agent configuration overwrite option

- ngrinder-frontend/src/js/components/user/UserInfo.vue
- ngrinder-frontend/src/js/components/user/modal/UserEditModal.vue
Prevent overflow of user information modal.
1. Before
2. After
> Prevent overflow of user information modal

- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-core/src/main/java/net/grinder/SingleConsole.java
- ngrinder-core/src/main/java/net/grinder/console/distribution/FileDistributionHandlerImplementation.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/FileStore.java
- ngrinder-core/src/main/java/net/grinder/engine/communication/DistFilesDigestMessage.java
- ngrinder-core/src/main/java/net/grinder/messages/agent/RefreshCacheMessage.java
- ngrinder-core/src/main/java/net/grinder/util/FileUtils.java
- ngrinder-core/src/main/java/org/ngrinder/common/util/PathUtils.java
- ngrinder-core/src/test/java/org/ngrinder/common/util/PathUtilsTest.java
Currently, when determine if the file is cached or not, ngrinder only use md5 checksum.
Therefore, if you run test using same script after changing the path, ngrinder controller recognizes that as a cached file and doesn't send it to the agent.
To resolve that, I changed file's digest format to `{relative path from base directory}:{md5 checksum}`.
> Change digest of cached files

- ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
Prevent overwriting of `agent.conf` when restarting agent.
> Prevent overwriting of agent.conf when restarting agent

- ngrinder-frontend/src/js/components/script/Editor.vue
- ngrinder-frontend/src/js/utils.js
When checking if the script is changed, new line character(`\n`, `\r\n`) should not affect the comparison result.
> Make script compared correctly

- ngrinder-frontend/src/js/components/script/Editor.vue
The splitpanes divides panes evenly on `mounted` hook, then calculate given pane size.
Prevent to flicker editor result console by disable the splitpanes transition css.
Reference: https://github.com/antoniandre/splitpanes/issues/80
> Prevent to flicker the script editor result console

- ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
- ngrinder-controller/src/main/java/org/ngrinder/common/constant/CacheConstants.java
- ngrinder-controller/src/main/java/org/ngrinder/home/service/HomeService.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-controller/src/main/java/org/ngrinder/script/service/FileEntryService.java
- ngrinder-controller/src/main/java/org/ngrinder/script/service/GitHubFileEntryService.java
- ngrinder-controller/src/main/java/org/ngrinder/user/service/UserService.java
- ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentServiceTest.java
- ngrinder-controller/src/test/java/org/ngrinder/agent/service/MockAgentService.java
Move cache of recently used agents to distribution map.
> Move cache of recently used agents to distribution map

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/SecurityConfig.java
- ngrinder-controller/src/main/resources/application.yml
When using H2 for the database of ngrinder, You can just pass `--spring.h2.console.enabled=true` as a environment variables to enable H2 console.
You can access via `{ip}:{port}/h2-console`
> Make the H2 console optionally available

- ngrinder-controller/src/main/java/org/ngrinder/infra/spring/UserHandlerMethodArgumentResolver.java
- ngrinder-controller/src/main/java/org/ngrinder/security/SecuredUser.java
- ngrinder-controller/src/main/java/org/ngrinder/security/UserSwitchPermissionVoter.java
- ngrinder-controller/src/main/java/org/ngrinder/user/controller/UserApiController.java
- ngrinder-controller/src/main/java/org/ngrinder/user/service/UserService.java
- ngrinder-core/src/main/java/org/ngrinder/model/User.java
Currently, we are using the `SecuredUser` object as a spring security's authentication principal.
It is used in some of our codes.
case of below, It emits `lazy initialize exception(no session)`.
because the `User` object stored in `SecuredUser` at login time is not properly initialized the fields that require lazy fetch.
so, I changed a `SecuredUser` to have eager fetched user object at login time.
```
SecuredUser secureUser = cast(authentication.getPrincipal());
User user = secureUser.getUser();
...
// Emit lazy initialize exception (no session)
List<User> owners = user.getOwners();
```
[Code snippet link](https://github.com/naver/ngrinder/blob/develop/ngrinder-controller/src/main/java/org/ngrinder/security/UserSwitchPermissionVoter.java#L56)
> Prevent lazy initialize exception in spring security authentication object

- ngrinder-frontend/src/js/components/script/Editor.vue
If the response body has HTML contents It rendered in the result console.
so the response body is escaped to prevent it.
> Escape response body in result console

- ngrinder-frontend/src/js/components/perftest/list/List.vue
Some global CSS affects to other component's style. so I limit  it's scope.
> Reduce range of global css

- ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
When a new test create & start, the test start button is flickered slightly because It's text is changed from`Save and Start` to `Clone and Start`. I adjusted button style to prevent It.
> Prevent test start button flickering

- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-core/src/main/java/net/grinder/StopReason.java
- ngrinder-core/src/main/java/org/ngrinder/model/Status.java
- ngrinder-core/src/main/java/org/ngrinder/model/StatusCategory.java
If user doesn't properly set a test recording(no recording) in the script. After the test is terminated, the test remains as abnormal testing state and can't stop(It can only delete). So, before updating as abnormal testing status, check if the test is stoppable.
1. Fix unstoppable abnormal test.
2. Add abnormal testing status category.
> Fix unstoppable abnormal test

- ngrinder-core/src/main/java/net/grinder/engine/communication/AgentUpdateGrinderMessage.java
After clean up all of the codes, the agent update message mistakenly became not-compatible b/w current controller and old agent. It's because the generated serialVersionUIDs were different from previous version. so I roll back the `AgentUpdateGrinderMessage` to make compatibility of old version agents.
> Fix java serialization conflict during agent update

- build.gradle
Add bintray gradle configuration to publish submodules.
It can be used like `./gradlew :ngrinder-groovy:bintrayUpload -PbintrayUser={bintray_user_id} -PbintrayKey={bintray_user_api_key} -PbintrayGpgPassphrase={bintray_user_gpg_private_key_passphrase}`
> Add bintray gradle configuration

- ngrinder-controller/src/main/resources/logback/logback-worker.xml
- ngrinder-runtime/src/main/resources/logback-worker.xml
Prevent to print debug or trace logs on `agent.log` file
```
2020-12-14 16:18:38,921 INFO  agent daemon: worker imb.local-0 started
2020-12-14 16:18:39,538 DEBUG org.xbill.DNS.config.JndiContextResolverConfigProvider$InnerJndiContextResolverConfigProvider: JNDI class: javax.naming.directory.DirContext
2020-12-14 16:18:39,566 DEBUG org.xbill.DNS.config.ResolvConfResolverConfigProvider: Added navercorp.com. to search paths
2020-12-14 16:18:39,566 DEBUG org.xbill.DNS.config.ResolvConfResolverConfigProvider: Added nhncorp.com. to search paths
2020-12-14 16:18:39,566 DEBUG org.xbill.DNS.config.ResolvConfResolverConfigProvider: Added nhnsystem.com. to search paths
2020-12-14 16:18:39,567 DEBUG org.xbill.DNS.config.ResolvConfResolverConfigProvider: Added nhncorp.jp. to search paths
2020-12-14 …
```
> Chaged not to print debug logs on agent.log

- ngrinder-controller/build.gradle
#657
Removed old version `jna-platform` to avoid loading competition.
> Fix script validation error in windows

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
Provide issue template.
1. In issues tab
If click the nGrinder community forum `open` button, It is linked to our discussions tab.
2. Template format
> Add issue template

- ngrinder-controller/build.gradle
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
- ngrinder-controller/src/main/java/org/ngrinder/script/handler/ScriptHandler.java
- ngrinder-core/build.gradle
- ngrinder-core/src/main/java/net/grinder/lang/jython/JythonGrinderClassPathProcessor.java
- ngrinder-runtime/build.gradle
- ngrinder-runtime/src/main/java/net/grinder/engine/process/GrinderProcess.java
- ngrinder-runtime/src/main/java/net/grinder/scriptengine/jython/JythonScriptEngineService.java
- ngrinder-runtime/src/main/java/net/grinder/scriptengine/jython/instrumentation/dcr/AbstractJythonDCRInstrumenter.java
- ngrinder-runtime/src/main/java/net/grinder/scriptengine/jython/instrumentation/dcr/Jython25Instrumenter.java
- ngrinder-runtime/src/main/java/net/grinder/scriptengine/jython/instrumentation/dcr/Jython27Instrumenter.java
Because the ASM version has been raised in [this](https://github.com/naver/ngrinder/pull/677/commits/80a8df1850e4d72a7c6f84d3df302c1b9fcd54a7) commit when you run Jython scripts with `jython-standalone:2.5.3` It emits `java.lang.VerifyError` at runtime. (It seems to be occurred when weaving)
So, bumped jython-standalone version up for compatibility with the latest version of ASM.
> This PR required more testing and must be merged before https://github.com/naver/ngrinder/pull/677
> Bump up Jython

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/TaskConfig.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/samplinglistener/PerfTestSamplingCollectorListener.java
- ngrinder-core/src/main/java/net/grinder/StopReason.java
- ngrinder-core/src/main/java/org/ngrinder/model/Status.java
- ngrinder-core/src/main/java/org/ngrinder/service/IPerfTestService.java
If there is a progressing state test(blue anime ball) when starting the controller. It becomes a zombie test.(delete only)
So, clean up all tests when starting the controller.
> Cancel progressing state test when starting controller

- ngrinder-controller/src/main/java/org/ngrinder/agent/controller/MonitorDownloadController.java
- ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentPackageService.java
- ngrinder-controller/src/main/java/org/ngrinder/packages/AgentPackageHandler.java
- ngrinder-controller/src/main/java/org/ngrinder/packages/MonitorPackageHandler.java
- ngrinder-controller/src/main/java/org/ngrinder/packages/PackageHandler.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/LocalScriptTestDriveService.java
- ngrinder-core/src/main/java/net/grinder/util/AbstractGrinderClassPathProcessor.java
- ngrinder-core/src/main/java/org/ngrinder/common/util/TypeConvertUtils.java
- ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java
From JDK9 the application class loader is no longer an instance of `java.net.URLClassLoader`
Therefore in a certain environment(run on Intellij), It emits `ClassCastException` when validating script.
> Fix validation error when using AppClassLoader in over JDK9

- ngrinder-frontend/package.json
Axios that we are using now, It has a critical [vulnerability](https://github.com/naver/ngrinder/security/dependabot/ngrinder-frontend/package.json/axios/open).
so that I bumped axios version up to the recommended version(patched version) of github security bot.
> Bump axios version up to avoid vulnerability

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/SecurityConfig.java
- ngrinder-frontend/src/js/components/Login.vue
Fix not working remember-me feature.
If you check the remember-me checkbox when you try to log-in the ngrinder, You can stay logged state when the session is expired or even the controller is restarted.
> Fix not working remember-me

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Database.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
- ngrinder-controller/src/main/java/org/ngrinder/starter/NGrinderControllerStarter.java
Make easy clustering only run in a single machine and `cluster-port ` is not a required option anymore.
If you run ngrinder on easy clustering It automatically clustered to localhost each other.
> Fix easy clustering

- ngrinder-controller/src/main/java/org/ngrinder/common/model/Home.java
- ngrinder-controller/src/main/java/org/ngrinder/common/util/FileUtils.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
- ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyGradleProjectScriptHandler.java
- ngrinder-controller/src/main/java/org/ngrinder/script/handler/ScriptHandler.java
- ngrinder-controller/src/main/java/org/ngrinder/script/service/FileEntryService.java
- ngrinder-controller/src/main/resources/script_template/groovy_gradle/src/main/java/TestRunner.groovy
- ngrinder-frontend/src/js/components/script/modal/CreateScriptModal.vue
In some cases, users want to modify the script template dynamically. so that I changed the way how ngrinder get the template files from resources.
1. When ngrinder is started, the `script_template` resources are copied to under `NGRINDER_HOME`. if `script_template` folder already exists in `NGRINDER_HOME` this step is skipped.
2. ngrinder get template resources from `NGRINDER_HOME/script_template` not from classpath:
> Support dynamic modification of script template

- ngrinder-controller/src/test/java/org/ngrinder/script/service/FileEntryServiceTest.java
Cause: The location where the controller to search script templates has changed from classpath to under ngrinder home.
So I changed the test to run in the spring context.
> In test context, ngrinder home is {java.io.tmpdir}/.ngrinder
> Fix failed test

- ngrinder-controller/build.gradle
- ngrinder-frontend/build.gradle
- ngrinder-frontend/webpack.config.js
1. Check es5 syntax at build time.
2. transpiled vuejs-datepicker because it contains the `const` keyword.
> const is fully supported by IE11 but caught by es-check. There seems to be no option to skip certain keywords.
> Add ES5 checking task to build cycle

- ngrinder-core/src/main/java/net/grinder/AgentController.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
- ngrinder-core/src/main/java/org/ngrinder/NGrinderAgentStarter.java
- ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
To support dynamic IP to a specific domain, when the agent re-reties to connect to a disconnected controller  It looks up controller IP from DNS.
> TTL properties refered to [AWS developer guide](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html)
> Look up controller ip from dns when agent re-tries to connect to controller

- ngrinder-frontend/package.json
- ngrinder-frontend/src/js/components/settings/WebhookSettings.vue
We are using [jsonc](https://www.npmjs.com/package/jsonc) module to parsing json string in FE.
this module recently making the below error and seems to be no longer updated.
so I drop the module and using javascript built-in object.
> Remove unnecessary json parser

- ngrinder-frontend/src/js/components/user/UserInfo.vue
Fix that user cannot search another user with two characters when configuring followers.
> Fix cannot search user with two characters

- ngrinder-frontend/.eslintrc.js
- ngrinder-frontend/package.json
Currently, even if there is no settings change, eslint make below error in all `.vue` files.
Because the [babel-eslint](https://www.npmjs.com/package/babel-eslint) we are currently using has been deprecated and has not been updated in the past 1 year.
So, I change eslint module to  [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser) that is replacement of [babel-eslint](https://www.npmjs.com/package/babel-eslint) to resolve errors from old modules.
> Change deprecated babel-eslint to new module

- ngrinder-frontend/src/js/components/agent/List.vue
Hide agent download link to general user in agent management page.
> Hide agent download link to general user in agent management page

- build.gradle
- gradle.properties
Because deprecation of JFlog Bintray, I change to use OSSRH for deployment ngrinder binary to maven central.
It deploys to the staging repository first, and the artifacts can be released to maven central after checking that they meet the maven central's requirements.
1. Fill in the commented properties in `gradle.properties`
3. Set `developer` settings in `build.gradle`
2. Run `./gradlew :ngrinder-{module_name}:uploadArchives`
> Change to use OSSRH for deployment ngrinder binary to maven central

- ngrinder-frontend/src/js/main.js
Fix #803
if `ngrinder.currentUser.timeZone` isn't set(no login), It use [moment.tz.guess()](https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/) for default value.
@lijie1010 Thanks for reporting.
> Fix that perftest detail report does not rendered properly if logout

- ngrinder-runtime/src/main/java/net/grinder/engine/process/GrinderThread.java
In Jython script, when the running test is terminated by shutdown signal `ShutdownException` is logged into agent logging message with error level. so users seem to be confused by that log. (many users ask me 'What is this error log?')
to reduce confusion, change logging level from error to info.
> I think `ShutdownException` from the worker thread is normal termination not error.
- Before
- After
> Change thread shutdown exception log level

- README.md
- ngrinder-controller/src/main/resources/messages_cn.properties
- ngrinder-controller/src/main/resources/messages_en.properties
- ngrinder-controller/src/main/resources/messages_kr.properties
- ngrinder-controller/src/test/java/org/ngrinder/home/service/HomeServiceTest.java
After change nabble URL, Q&A pannel is loaded .
#825
> [#825] Change nabble forum URL

- ngrinder-controller/build.gradle
- ngrinder-frontend/build.gradle
Resolved: #895
Main role of the `es-check` task was to detect IE compatibility issues.
Since the IE has retired, remove the `es-check` task. 
We expect that the most of modern web browers are compatible.
> Remove es-check gradle task

- ngrinder-frontend/src/js/components/script/Editor.vue
Resolve  #884
Sometimes script contents are missing after validation check.
This error can be reproduced by steps described below.
1. Edit script contents
2. Save the script
3. Edit script contents
4. Validate the script
There're no codes to change or assign the script contents in script validation function.
This error looks like a timing issue that caused by handling vue component status on both child and parent.
After chaning the script contents assigning to child component method invocation, the error case is not occured anymore in my environment.
> Fix the script content is lost after validation check

- build.gradle
Change `scm-manager` maven repository URL.
* Before: https://maven.scm-manager.org/nexus/content/repositories/releases
* After : https://packages.scm-manager.org/repository/releases
When enter the before URL on a web browser, it redirects to the after URL.
I think the before URL is no more supported. 
I checked that gradle can resolve the svnkit dependency after changing the maven repo URL.
But, [maven respository official website](https://mvnrepository.com/repos/scm-manager-releases) still introduces the legacy URL. It confuse me...
> Fix scm-manager maven repo url

- ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/task/RegionInfoTask.java
- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
- ngrinder-controller/src/main/java/org/ngrinder/region/service/RegionService.java
- ngrinder-controller/src/test/java/org/ngrinder/infra/config/DynamicCacheConfigTest.java
- ngrinder-core/src/main/java/net/grinder/engine/agent/AgentImplementationEx.java
- ngrinder-core/src/main/java/net/grinder/util/NetworkUtils.java
- ngrinder-core/src/main/java/org/ngrinder/NGrinderAgentStarter.java
- ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
- ngrinder-core/src/test/java/net/grinder/util/NetworkUtilTest.java
resolved: https://github.com/naver/ngrinder/issues/885
On macOS, `InetAddress.getLocalHost()` returns weired address and it derives no port available exception. 
Available port check is executed with the wrong IP address, so the controller can not acquire any ports.
---
After digging a few days, It comes out not an application bug, it is a kind of PC settings issue.
No major logic changes in this PR. I just make it clearer how to deal with this issue.
> Add InetAddress reachable check

- docker/README.md
- docker/agent/Dockerfile
I tried to release Docker images and tested v3.5.6. But, there is a little problem on agent running.
Related issue is https://github.com/oshi/oshi/issues/271. 
The agent can not run with printing error log below.
<details><summary>Click to see error log</summary>
<p>
```
Connecting to ___.___.___.___:80 (___.___.___.___:80)
Connecting to ___.___.___.___ (___.___.___.___:80)
ngrinder-agent.tar   100% |****************************************************| 76.0M  0:00:00 ETA
ngrinder-agent/
ngrinder-agent/lib/
ngrinder-agent/run_agent_bg.sh
ngrinder-agent/stop_agent.sh
ngrinder-agent/run_agent.bat
ngrinder-agent/run_agent_internal.bat
ngrinder-agent/run_agent.sh
ngrinder-agent/run_agent_internal.sh
ngrinder-agent/stop_agent.bat
ngrinder-agent/lib/ngrinder-core-3.5.6.jar …
```
> Fix docker agent set up

- ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyGradleProjectScriptHandler.java
- ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyProjectScriptHandler.java
- ngrinder-controller/src/main/java/org/ngrinder/starter/InstallationChecker.java
Recently, nGrinder bumps Oshi from `5.2.2` to `6.1.6`.
And Oshi changes the `runNative()` method to pass environment variables.
`runNative()` method is a wrapper of `Runtime.getRuntime().exec()` that captures the output in a list.
```java
public static List<String> runNative(String[] cmdToRunWithArgs) {
return runNative(cmdToRunWithArgs, DEFAULT_ENV); // DEFAULT_ENV == "LC_ALL=C"
}
```
This change makes executing gradle goes wrong. So, I changed to pass nothing as environment variable.
> Fix gradle command execution on Oshi 6.x

- ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPRequest.java
If the new HTTPRequest's `setReadBytes()` method is invoked in `@BeforeProcess`, the IOReactor is not closed and it dervies memory leak. So, close it appropriately.
> Prevent memory leak on HTTPRequest

- ngrinder-frontend/src/js/components/perftest/detail/Config.vue
There is a bug related to Select2 version up.
* Revision is always set as `HEAD` whenever creating a new test or checking the test alread done.
* Target hosts field is always set as equal to script's target hosts setting. 
Setting the target hosts in perftest config menu is not affected.
These two bugs are caused by triggering `change` event at the initial rendering.
Fix these bugs by removing the selection of the initial script selecting.
> Fix revision and target hosts reset

- ngrinder-controller/src/main/java/org/ngrinder/common/constant/ConsoleColorConstants.java
- ngrinder-controller/src/main/java/org/ngrinder/starter/InstallationChecker.java
- ngrinder-controller/src/main/java/org/ngrinder/starter/NGrinderControllerStarter.java
resolve: #848
If running on tomcat, `NGrinderControllerStarter.main()` will not be invoked.
If running on SpringBoot JAR, check the `tmpdir` system property and exit if the property is not specified.
Warning message shows like this.
> Add warning message when running without tmpdir property

- docker/README.md
I want to add description about purpose of 16001 port.
I referenced the `org.ngrinder.starter.NGrinderControllerStarter` class of ngrinder-controller module.
> Add description about agent connection port to docker README.md

- ngrinder-controller/src/main/java/org/ngrinder/common/constant/ControllerConstants.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
- ngrinder-controller/src/main/resources/controller-properties.map
- ngrinder-core/src/main/java/net/grinder/util/NetworkUtils.java
controller.ip property was used even after this property has changed its name to controller.host.
Fix this
> Use controller.host property instead of old controller.ip property

- ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
- ngrinder-core/src/main/java/net/grinder/SingleConsole.java
Add fallback to cleanup perftest resources.
> Add fallback to cleanup perftest resources

- ngrinder-controller/build.gradle
- ngrinder-controller/src/main/java/org/ngrinder/script/service/GitHubFileEntryService.java
- ngrinder-controller/src/test/java/org/ngrinder/script/service/GitHubFileEntryServiceTest.java
snakeyaml 1.x has security vulnerability. So, I tried to bump it up to 2.x. But, the snakeyaml is related to spring framework also. When the snakeyaml is found on classpath, spring try to use the given snakeyaml to handling yaml property file.
Most of spring-boot versions are depend on snakeyaml 1.x except latest version of spring-boot. I think that upgrade spring-boot to latest version will take long time. So, just change the yaml parser to [yamlbeans](https://github.com/EsotericSoftware/yamlbeans) that has most stars library in [yaml official website](https://yaml.org/) except snakeyaml.
> Change yaml parser to yamlbeans

- ngrinder-controller/src/main/java/org/ngrinder/agent/controller/MonitorManagerApiController.java
- ngrinder-controller/src/main/java/org/ngrinder/common/constant/ControllerConstants.java
- ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
- ngrinder-controller/src/main/resources/controller-properties.map
- ngrinder-controller/src/main/resources/ngrinder_home_template/system.conf
- ngrinder-frontend/src/js/components/perftest/modal/TargetHostInfoModal.vue
Add controller properties for monitoring enable or not
> Add controller properties for monitoring enable or not

- ngrinder-controller/src/test/java/org/ngrinder/perftest/service/PerfTestRunnableTest.java
- ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java
- ngrinder-core/src/test/java/net/grinder/AgentControllerTest.java
- ngrinder-core/src/test/java/org/ngrinder/AbstractMultiGrinderTestBase.java
- ngrinder-core/src/test/java/org/ngrinder/infra/AgentConfigTest.java
> Fix unit test

- .github/workflows/run-build-with-test-on-pr.yml
- build.gradle
- ngrinder-core/src/main/java/net/grinder/communication/Connector.java
- ngrinder-runtime/src/main/java/org/ngrinder/dns/LocalManagedDnsImpl.java
And bump target JDK version up to 11 also.
> Add object input filter on Connector

- ngrinder-controller/src/main/java/org/ngrinder/starter/InstallationChecker.java
- ngrinder-controller/src/test/java/org/ngrinder/starter/InstallationCheckerTest.java
There were two major factors causing this bug.
1. Calling `System.getenv()` on initializing enums was failed on Windows.
2. Getting the standard output of the process using `oshi.util.ExecutingCommand.runNative()` was failed on Windows due to Linux-specific command scripts.
1. Changed the time calling `System.getenv()` after initializing.
2. Set OS specific command scripts checking installation using `com.sun.jna.Platform.isWindows()`.
Since `com.sun.jna.Platform` sets the static values of current OS on start, no needed to call `System.getProperty("os.name")` again.
But considered that the dependency including `com.sun.jna.Platform` may be removed in future, it could be the best option to check by calling `System.getProperty("os.name")`.
> Fix failing to call mvn or gradle at MAVEN_HOME, GRADLE_HOME respectively in Windows (Resolves #975)
