ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
ngrinder-controller/src/main/webapp/js/utils.js
ngrinder-core/src/main/java/org/ngrinder/infra/AgentConfig.java

- Selector more detail for popover target
- Modify condition of "agent.conf" overwrite

modify popover target & conditions overwrite "agent.conf"

---

docker/agent/Dockerfile
docker/agent/scripts/run.sh
docker/controller/Dockerfile
docker/controller/scripts/run.sh

Dear nGrinder developers, 
I have added 4 docker-related files (Dockerfiles and run scripts for both controller and agent).
Controller can be run with the following command:
```
docker run -d -v ~/.ngrinder:/root/.ngrinder -p 80:80 -p 16001:16001 -p 12000-12009:12000-12009 ngrinder/controller
```
Agents can be run with the following command:
```
docker run -d -e 'CONTROLLER_ADDR=[controller_ip:web_port]' ngrinder/agent
```

add docker files

---

ngrinder-controller/src/main/java/org/ngrinder/common/constant/ControllerConstants.java
ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
ngrinder-controller/src/main/java/org/ngrinder/operation/cotroller/StatisticsController.java
ngrinder-controller/src/main/resources/controller-properties.map
ngrinder-controller/src/main/resources/ngrinder_home_template/system.conf

Provide statistics of ngrinder web server.

add statistics data API for JVM, ehcache, dbcp

---

ngrinder-controller/pom.xml
ngrinder-core/pom.xml
ngrinder-groovy/pom.xml
ngrinder-runtime/pom.xml
ngrinder-sh/pom.xml
ngrinder-starter/pom.xml
pom.xml
release_note.txt

3.4 (2015.11.06)
nGrinder 3.4 is the including function statistics API and auto create script.
- New feature and changes
* Statistics API
- You can monitoring JVM, Ehcache, dbcp statistics of nGrinder web server.
- If you want use, need enable "controller.enable_statistics" in system.conf.
* Easy generate script
- You can do scripting header/cookie/parameter for send request, in a simple setting.
* nGrinder recorder(Chrome extension)
- Chrome extension program.
- If you used chrome browser, install extension in "ngrinder/ngrinder-recorder"
- Recorder do record request in browser, and auto create script.

Prepare nGrinder 3.4 release

---

ngrinder-controller/src/main/resources/script_template/basic_template_groovy.ftl
ngrinder-controller/src/main/resources/script_template/basic_template_py.ftl

#85 TPS is the counting double.

---

ngrinder-controller/pom.xml
ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
ngrinder-controller/src/main/java/org/ngrinder/security/DefaultLoginPlugin.java
ngrinder-controller/src/main/java/org/ngrinder/security/NGrinderAuthenticationProvider.java
ngrinder-controller/src/main/java/org/ngrinder/user/controller/UserController.java
ngrinder-controller/src/main/resources/applicationContext-ehcache.xml
ngrinder-controller/src/main/resources/applicationContext-external.xml
ngrinder-controller/src/main/resources/applicationContext-message.xml
ngrinder-controller/src/main/resources/applicationContext-security.xml
ngrinder-controller/src/main/resources/applicationContext-springdata.xml
ngrinder-controller/src/main/resources/applicationContext-task.xml
ngrinder-controller/src/main/resources/applicationContext.xml
ngrinder-controller/src/main/resources/servlet-context.xml
ngrinder-controller/src/main/webapp/WEB-INF/ftl/common/navigator.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/common/spring.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/config.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/script/editor.ftl
ngrinder-controller/src/main/webapp/WEB-INF/security.tld
pom.xml

This is the pull request for JDK8 support.
Underlying Spring is upgraded to 4.1

add jdk8 support

---

ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java
ngrinder-controller/src/main/java/org/ngrinder/agent/repository/AgentManagerSpecification.java
ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentManagerService.java
ngrinder-controller/src/main/java/org/ngrinder/agent/service/ClusteredAgentManagerService.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
ngrinder-controller/src/main/resources/messages_cn.properties
ngrinder-controller/src/main/resources/messages_en.properties
ngrinder-controller/src/main/resources/messages_kr.properties
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/config.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
ngrinder-controller/src/test/java/org/ngrinder/agent/controller/AgentManagerControllerTest.java
ngrinder-controller/src/test/java/org/ngrinder/agent/repository/AgentRepositoryTest.java
ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentManagerServiceTest.java
ngrinder-controller/src/test/java/org/ngrinder/agent/service/ClusteredAgentManagerServiceTest.java
ngrinder-controller/src/test/java/org/ngrinder/perftest/controller/PerfTestControllerTest.java
ngrinder-core/src/main/java/net/grinder/message/console/AgentControllerState.java
ngrinder-core/src/main/java/org/ngrinder/service/IAgentManagerService.java

- The use of cluster mode and single-mode exposure quantity agents
- TC create

 Quantity of the available agents according to the area value of exposure

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl

- detail.ftl append envent trigger('mouseover')

 Test Failed Pause agent popup log exposure

---

ngrinder-controller/src/main/resources/messages_cn.properties

Fixed Chinese Translation

---

ngrinder-controller/src/test/java/org/ngrinder/agent/repository/AgentRepositoryTest.java
ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentManagerServiceTest.java
ngrinder-controller/src/test/java/org/ngrinder/agent/service/ClusteredAgentManagerServiceTest.java

- Add a status value to the agent test method.
- Test code to delete duplicate.
@junoyoon @GwonGisoo  Please review the code.
thank you.

agentManagerService TC Refactoring

---

ngrinder-controller/pom.xml
ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryController.java
ngrinder-controller/src/main/resources/lucy-xss-servlet-filter-rule.xml
ngrinder-controller/src/main/resources/lucy-xss-superset-sax.xml
ngrinder-controller/src/main/webapp/WEB-INF/ftl/common/navigator.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl
ngrinder-controller/src/main/webapp/WEB-INF/web.xml

- Fix ngrinder security Modified.

#103 Fix security issue

---

.travis.yml

#109 Setting a TravisCI

---

ngrinder-controller/src/main/java/org/ngrinder/common/constant/ControllerConstants.java
ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
ngrinder-controller/src/main/resources/controller-properties.map
ngrinder-controller/src/main/resources/ngrinder_home_template/system.conf
ngrinder-core/src/main/java/net/grinder/SingleConsole.java

- system.conf append CSV file format option.
(Change according to the setting value.)

 #73 configurable CSV separator

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/service/samplinglistener/MonitorCollectorPlugin.java

- bufferedWriter close Modified.

#98 Unable to display target hosts data in detail report page.

---

ngrinder-controller/src/main/resources/messages_cn.properties
ngrinder-controller/src/main/resources/messages_en.properties

Translate Chinese and fix some errors

---

ngrinder-controller/src/main/java/org/ngrinder/common/util/EncodingUtils.java
ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryController.java
ngrinder-controller/src/test/java/org/ngrinder/common/util/EncodingUtilsTest.java

@songeunwoo  Please review this.

#134 Chinese in url

---

ngrinder-controller/src/main/resources/META-INF/persistence.xml

Hibernate settings are fixed to remove warning.

#127 fix hibernate warning

---

deploy_ngrinder_core.sh
ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
ngrinder-groovy/src/main/java/net/grinder/engine/process/JavaDCRInstrumenterEx.java
ngrinder-groovy/src/main/java/net/grinder/scriptengine/groovy/GroovyScriptEngineService.java
ngrinder-groovy/src/main/java/net/grinder/scriptengine/groovy/junit/RepetitionStatement.java
ngrinder-groovy/src/main/java/net/grinder/scriptengine/groovy/junit/annotation/Repeat.java
ngrinder-groovy/src/main/java/net/grinder/util/GrinderUtils.java
pom.xml

Publish ngrinder 3.4 maven lib into maven repo.

#136 Publish ngrinder 3.4 maven lib into maven repo

---

ngrinder-controller/src/main/java/org/ngrinder/home/service/HomeService.java
ngrinder-controller/src/main/resources/controller-properties.map
ngrinder-controller/src/main/resources/ngrinder_home_template/system.conf
ngrinder-controller/src/test/java/org/ngrinder/home/service/HomeServiceTestWithAtom.java
pom.xml

Change developer resources rss addr to github

#149 change developer resources rss addr to github

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/common/copyright.ftl
ngrinder-groovy/src/main/java/net/grinder/scriptengine/groovy/GroovyScriptEngineService.java
ngrinder-groovy/src/test/java/net/grinder/scriptengine/groovy/GrinderRunnerTest.java
ngrinder-groovy/src/test/java/net/grinder/scriptengine/groovy/GroovyScriptEngineTest.java

- move ngrinder link to github

#147 move ngrinder link to github

---

ngrinder-controller/pom.xml
pom.xml

#151 make agent java run in 1.6

---

ngrinder-controller/src/main/java/org/ngrinder/home/service/HomeService.java

In case that atom feed provide the item link, we should use this link.

#149 Fix bug

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl

* make each perftest page number start with 0
* align ftl files.

#156 Fix test search error

---

ngrinder-controller/src/main/java/org/ngrinder/common/controller/BaseController.java
ngrinder-controller/src/main/java/org/ngrinder/user/controller/UserController.java
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/user/list.ftl

fix sort param mapping in user. I fixed this on perftest as well.

#160 Fix user search error

---

ngrinder-controller/src/main/java/org/ngrinder/home/service/HomeService.java

 #149 modify github wiki uri.

---

ngrinder-controller/pom.xml
ngrinder-core/pom.xml
ngrinder-groovy/pom.xml
ngrinder-runtime/pom.xml
ngrinder-sh/pom.xml
ngrinder-starter/pom.xml
pom.xml

prepare 3.4.1

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl

#168 provide better test navigation

#168 provide better test navigation

---

.editorconfig

provide editor config to make code consistent

provide editor config to make code consistent

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/index.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/detail.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/list.ftl
ngrinder-controller/src/main/webapp/WEB-INF/ftl/script/editor.ftl

add tip style

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/user/list.ftl

modify page-navigatable.

---

ngrinder-controller/src/main/resources/ngrinder_agent_home_template/agent_monitor.conf

#177 modify agent_monitor.conf

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/script/create_script_modal.ftl

- modify github wiki resources url.

#186 Modify the wrong link.

---

ngrinder-controller/src/main/java/org/ngrinder/infra/plugin/PluginManager.java
ngrinder-controller/src/main/java/org/ngrinder/infra/plugin/extension/NGrinderDefaultPluginManager.java
ngrinder-controller/src/main/java/org/ngrinder/infra/plugin/extension/NGrinderSpringExtensionFactory.java
ngrinder-controller/src/main/java/org/ngrinder/infra/plugin/finder/NGrinderDefaultExtensionFinder.java

This fix includes the issue on #184 
@songeunwoo  Please run this on our dev-cluster with plugins.

#184 fix circular injection

---

ngrinder-controller/src/main/java/org/ngrinder/script/service/FileEntryService.java

the params may be null, and this will cause the null pointer.

fix bug when har file has no params

---

ngrinder-core/src/main/java/org/ngrinder/monitor/share/domain/BandWidth.java

Fix bug of bandWidth calculation method
I referred to #285.

Fix bug of bandWidth calculation method

---

RELEASE-NOTE.md

typo-fixed

---

index.html

typo LICENCE -> LICENSE

---

ngrinder-core/src/main/java/net/grinder/engine/agent/LocalScriptTestDriveService.java
ngrinder-core/src/main/java/net/grinder/engine/agent/ValidationPropertyBuilder.java
ngrinder-runtime/src/main/java/org/ngrinder/sm/NGrinderSecurityManager.java

I modified NGrinderSecurityManager read access. It will work like this.
1. ngrinder controller
- Restrict read access for ngrinder home. but user can access their work and tmp folder in there
2. ngrinder agent
- No restrict

Modify NGrinderSecurityManager read access 

---

.editorconfig

Use crlf for end of line not to break the diff

Use crlf for end of line

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/ClusteredAgentManagerService.java
ngrinder-controller/src/main/java/org/ngrinder/infra/config/Config.java

Clean up test log

---

ngrinder-controller/pom.xml
ngrinder-core/pom.xml
ngrinder-groovy/pom.xml
ngrinder-runtime/pom.xml
ngrinder-sh/pom.xml
ngrinder-starter/pom.xml
pom.xml

Update nGrinder snapshot version 3.4.1 to 3.4.2

Update nGrinder version as 3.4.2-SNAPSHOT

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/agent/list.ftl

Add local variable to agent list for check the admin

Add local variable to agent list for check the admin

---

ngrinder-controller/src/main/webapp/WEB-INF/ftl/perftest/config.ftl

Fix ramp-up section layout error when selecting region in perftest conf.

Fix invalid rampup section layout

---

ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java

Fix agent filtering logic when `All` region in cluster mode

Fix agent filtering logic

---

build.gradle
ngrinder-controller/build.gradle
ngrinder-core/build.gradle
ngrinder-groovy/build.gradle
ngrinder-runtime/build.gradle

Currently unnecessary libs are overlaid. So I remove that from overlay.

Optimize overlay dependencies

---

ngrinder-controller/src/main/java/org/ngrinder/security/NGrinderAuthenticationProvider.java

#357
Use lazy loading for resolve circular dependency issue.
I confirmed this in windows and mac.

Use lazy loading for resolve circular dependency issue

---

ngrinder-controller/build.gradle
ngrinder-controller/src/main/java/org/ngrinder/infra/config/Database.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ConsoleManager.java
ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog.xml
ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_28.xml
ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_29.xml
ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_H2.xml
ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_MYSQL.xml

Added timestamp data type default value to H2.

Make null as a default value for created/modified timestamp 

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java

Change `threadhold` to` threshold`.

Fix typo "Threadhold" -> "Threshold"

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java

Fix incorrect unit `1204` -> `1024`

Fix calculation of log limit size

---

ngrinder-controller/src/main/resources/templates/ftl/perftest/running.ftl

Fix wrong html closing tag

---

ngrinder-controller/src/main/java/org/ngrinder/common/service/ModelAspect.java

In user switching mode, set factual user as created user before saving perftest

Set factual user as created user before saving perftest

---

ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue

1. Fixed bug that override existing test data when test clone.
2. Automatic updating of perftest lists will work only for non-finished test.

Bug fix in perftest list and detail

---

ngrinder-controller/src/test/java/org/ngrinder/perftest/controller/PerfTestControllerWithRepoTest.java

Fix failed Test

---

ngrinder-frontend/src/html/app.html
ngrinder-frontend/src/js/components/Base.vue
ngrinder-frontend/src/js/components/common/mixin/MessagesMixin.vue
ngrinder-frontend/src/js/components/operation/Announcement.vue
ngrinder-frontend/src/js/components/operation/SystemConfig.vue
ngrinder-frontend/src/js/components/perftest/detail/Running.vue
ngrinder-frontend/src/js/components/perftest/detail/SamplingTable.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/perftest/mixin/FormatMixin.vue
ngrinder-frontend/src/js/components/perftest/report/menu/Monitor.vue
ngrinder-frontend/src/js/components/script/Editor.vue
ngrinder-frontend/src/js/components/user/UserDetail.vue
ngrinder-frontend/src/js/main.js

Move messages component to global scope, and access this component from `MessagesMixin`.

Move messages component to global scope

---

ngrinder-controller/build.gradle
ngrinder-frontend/package.json

Change gradle build-output directory path for matching with webpack output path.

Change gradle build-output directory path for matching with webpack output path

---

tools/migrator/exclude-fields.json
tools/migrator/lib/migrate-cubrid-to-mysql.js
tools/migrator/package.json

- Fix mysql security vulnerability
- Add exclusion columns when migrating

Fix mysql security vulnerability

---

ngrinder-controller/src/test/java/org/ngrinder/perftest/service/ConsoleManagerTest.java
ngrinder-core/src/test/java/net/grinder/engine/agent/PropertyBuilderTest.java
ngrinder-core/src/test/java/org/ngrinder/monitor/collector/MonitorCollectorTest.java

[Merge into master]
Use network interface before monitor collection test.

Fix failed tests

---

RELEASE-NOTE.md
ngrinder-controller/pom.xml
ngrinder-core/pom.xml
ngrinder-groovy/pom.xml
ngrinder-runtime/pom.xml
ngrinder-sh/pom.xml
ngrinder-starter/pom.xml
pom.xml

- Change ngrinder version to 3.4.3
- This release fixes log rolling error and xss filter error

Release version 3.4.3

---

ngrinder-controller/src/main/java/org/ngrinder/common/util/JsonUtils.java
ngrinder-controller/src/main/java/org/ngrinder/infra/config/NumberModule.java
ngrinder-controller/src/main/java/org/ngrinder/infra/config/WebMvcConfig.java
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/test/java/org/ngrinder/common/util/JsonUtilsTest.java
ngrinder-frontend/src/js/components/perftest/mixin/FormatMixin.vue

- Sometimes cpu usage percentage presents as NaN
- There's no NaN in JSON format, represent it as null

Serialize JSON NaN as null

---

ngrinder-controller/src/main/java/org/ngrinder/common/controller/GlobalControllerAdvice.java
ngrinder-frontend/src/html/app.html
ngrinder-frontend/src/js/components/Base.vue
ngrinder-frontend/src/js/components/Home.vue
ngrinder-frontend/src/js/components/HomePanel.vue
ngrinder-frontend/src/js/components/Login.vue
ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/common/navigator/Navigator.vue
ngrinder-frontend/src/js/components/common/navigator/UserMenu.vue
ngrinder-frontend/src/js/components/common/navigator/modal/UserSwitchModal.vue
ngrinder-frontend/src/js/components/perftest/detail/Config.vue
ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
ngrinder-frontend/src/js/components/perftest/detail/Report.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/script/List.vue
ngrinder-frontend/src/js/components/script/SearchBar.vue
ngrinder-frontend/src/js/components/script/mixin/TableConfig.vue
ngrinder-frontend/src/js/components/user/List.vue
ngrinder-frontend/src/js/main.js
ngrinder-frontend/webpack.config.js

Add context path to resource url.

Add context path to resource url

---

ngrinder-frontend/package.json

https://github.com/naver/ngrinder/network/alerts
1. axios : version up
2. debug : remove (not used)
-  I'll add it later if needed.

Resolve security alert

---

ngrinder-frontend/src/js/components/Home.vue
ngrinder-frontend/src/js/components/HomePanel.vue
ngrinder-frontend/src/js/components/common/IntroButton.vue
ngrinder-frontend/src/js/components/common/navigator/Navigator.vue
ngrinder-frontend/src/js/components/common/navigator/UserMenu.vue
ngrinder-frontend/src/js/components/common/navigator/modal/UserSwitchModal.vue
ngrinder-frontend/src/js/components/script/SearchBar.vue

Clean up front-end codes

---

ngrinder-controller/src/main/java/org/ngrinder/common/constant/WebConstants.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestApiController.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
ngrinder-frontend/src/js/components/Home.vue
ngrinder-frontend/src/js/components/common/Autocomplete.vue
ngrinder-frontend/src/js/components/perftest/detail/Config.vue
ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
ngrinder-frontend/src/js/components/perftest/detail/DurationSlider.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
ngrinder-frontend/src/js/components/perftest/modal/ScheduleModal.vue
ngrinder-frontend/src/js/components/script/Editor.vue
ngrinder-frontend/src/js/components/script/List.vue
ngrinder-frontend/src/js/components/user/List.vue
ngrinder-frontend/src/js/main.js

- Make data ready before rendering script list, script editor and perftest detail
- Fix bug that cannot refresh on quickstart

Ensure data ready before rendering

---

ngrinder-controller/src/main/java/org/ngrinder/agent/controller/AgentManagerController.java
ngrinder-frontend/src/js/components/agent/Detail.vue
ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue

- Enable to refresh on agent detail page

Resolve agent via props

---

ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/script/Editor.vue

Fix script detail link in perftest list

---

ngrinder-frontend/src/js/main.js

- There is a bug that popovers are remained and not cleared
- To resolve it, clear popover on each routing

Clear popover on before each routing

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentManagerService.java
ngrinder-controller/src/main/java/org/ngrinder/agent/service/ClusteredAgentManagerService.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/AgentManager.java
ngrinder-core/src/main/java/org/ngrinder/model/AgentInfo.java
ngrinder-frontend/src/js/components/agent/mixin/TableConfig.vue
ngrinder-frontend/src/js/components/common/navigator/UserMenu.vue

Support agent management menu for normal user.
1. show `public agent` and `their owned agent`
2. handle wrong region for owned agent.

Support agent management menu for normal user

---

ngrinder-frontend/src/js/components/script/SearchBar.vue

Apply text ellipsis to svn link.

Apply text ellipsis to svn link

---

ngrinder-controller/src/main/resources/static/css/ngrinder.css
ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java
ngrinder-frontend/src/js/components/common/InputAppend.vue
ngrinder-frontend/src/js/components/common/InputLabel.vue
ngrinder-frontend/src/js/components/common/InputPrepend.vue
ngrinder-frontend/src/js/components/common/mixin/ChartMixin.vue
ngrinder-frontend/src/js/components/perftest/detail/Config.vue
ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
ngrinder-frontend/src/js/components/perftest/detail/RampUp.vue
ngrinder-frontend/src/js/components/perftest/detail/Running.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/main.js
ngrinder-frontend/src/js/vee-validate-initializer.js

- Allow to change the fields of test object passed from parent component
- Remove getParams() methods in child components
- Serialize/deserialize test object in the parent component

Remove copy props pattern in perftest detail

---

ngrinder-controller/src/main/java/org/ngrinder/infra/spring/RemainedPathMethodArgumentResolver.java
ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryApiController.java
ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryController.java
ngrinder-controller/src/test/java/org/ngrinder/script/controller/FileEntryApiControllerTest.java
ngrinder-frontend/package.json
ngrinder-frontend/src/js/components/script/List.vue

- Make utf-8 file name doesn't break on file download
- Support IE11, Safari, Chrome

Make file name encoded with utf-8 on file download

---

RELEASE-NOTE.md
ngrinder-controller/pom.xml
ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
ngrinder-core/pom.xml
ngrinder-groovy/pom.xml
ngrinder-runtime/pom.xml
ngrinder-sh/pom.xml
ngrinder-starter/pom.xml
pom.xml

Fix maven central repository url to https

---

ngrinder-frontend/src/js/components/Base.vue
ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue

Use popover to display current agent state.

Use popover to display current agent state

---

ngrinder-core/src/main/java/net/grinder/engine/agent/PropertyBuilder.java

Add SSL related JVM arguments before running worker process.

Add SSL related JVM arguments before running worker process

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
ngrinder-controller/src/main/java/org/ngrinder/infra/hazelcast/task/AgentStateTask.java
ngrinder-core/src/main/java/net/grinder/console/communication/AgentProcessControlImplementation.java

Currently agent status messages(cpu, mem, rx, etc..) are not being updated properly on running phase.
So, I fix that.

Fix agent status reporting message updation logic

---

ngrinder-controller/pom.xml
ngrinder-controller/src/main/java/org/ngrinder/agent/service/ClusteredAgentManagerService.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestController.java
ngrinder-controller/src/main/java/org/ngrinder/script/controller/FileEntryController.java
ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyMavenProjectScriptHandler.java

- use default repository url as `https://repo1.maven.org/maven2/`
- `MavenCli.MULTIMODULE_PROJECT_DIRECTORY` property must be set to prevent maven exit exception
- also bump up guava to 20.0 to resolve dependency conflict

Bump up maven-embedder 3.6.3

---

.mvn/wrapper/maven-wrapper.properties
pom.xml

Bump up maven wrapper to 3.6.3

Bump up maven wrapper to 3.6.3

---

RELEASE-NOTE.md

Fix release note

---

ngrinder-frontend/src/js/components/Home.vue
ngrinder-frontend/src/js/components/HomePanel.vue

Add resource url link to home panel.

Add resource url link to home panel

---

ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java

Fix hazelcast network config to use only one port
Ref: https://docs.hazelcast.org//docs/latest/manual/html-single/index.html#port

Fix hazelcast network config

---

ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
ngrinder-frontend/src/js/main.js
ngrinder-frontend/src/js/store/vuex-store.js

Fix case where admin couldn't look user's scripts up in perftest detail.
- Appended `ownerId` to query string of getting scripts API when admin look normal user's test up.

Fix prepare scripts in perftest detail

---

ngrinder-frontend/src/js/components/perftest/detail/Config.vue
ngrinder-frontend/src/js/components/perftest/detail/DurationSlider.vue
ngrinder-frontend/src/js/components/perftest/detail/Report.vue
ngrinder-frontend/src/js/components/perftest/detail/SamplingTable.vue
ngrinder-frontend/src/js/components/perftest/report/DetailReport.vue

1. Fix #522
2. Fix #523
3. Fix #525
4. Open perftest detail report in new browser tab.

Fix data output correctly

---

ngrinder-frontend/src/js/components/script/Editor.vue

* Fix CSS to make editor properly works in Safari browser

Make editor CSS and split panes compatible in Safari

---

ngrinder-frontend/src/js/components/script/Editor.vue

Resolved
- Browser console error.
- Editor initialization code works correctly.

Set target hosts when only exist

---

gradle/wrapper/gradle-wrapper.properties
ngrinder-frontend/build.gradle

Bump gradle wrapper up to 6.3.

Bump gradle wrapper up to 6.3

---

ngrinder-controller/src/main/java/org/ngrinder/infra/config/WebMvcConfig.java
ngrinder-controller/src/main/resources/application.yml

Use spring boot multipart configuration.

Use spring boot multipart configuration

---

build.gradle

Fix profile settings in build script

Fix profile settings in build script

---

ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/agent/mixin/TableConfig.vue

- Remove agent management buttons when the role is user
- Change not to set the state of un-rendered agents

Improve agent management view on user role

---

ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/script/List.vue
ngrinder-frontend/src/js/components/user/List.vue

- increase pagination size 5 to 11
- on each size 5 means the slide size on each side of the center

Increase pagination size

---

ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/script/List.vue
ngrinder-frontend/src/js/components/user/List.vue

- Prevent to print console error by using different type parameter
- Change parameter type String to Number

Fix vue table pagination parameter type

---

ngrinder-frontend/src/js/components/script/Editor.vue

Adjust editor console size

---

ngrinder-frontend/src/js/components/perftest/report/menu/Monitor.vue
ngrinder-frontend/src/js/components/perftest/report/menu/PerfTest.vue

Make detail report more natural.

Make detail report more natural

---

ngrinder-core/src/main/java/org/ngrinder/model/PerfTest.java

In perftest save api emit NPE when attach file revision. so i fix that.

Prevent NPE when attach file revision

---

ngrinder-frontend/src/js/utils.js

- first, trying to detect locale from local storage
- second, trying to detect locale from cookie
- default, set locale to "en"

Set default locale to "en" when fail to detect user locale

---

ngrinder-frontend/src/js/components/agent/List.vue
ngrinder-frontend/src/js/components/agent/modal/AddConnectionAgentModal.vue

- reset page when region filter is changed

Fix agent list pagination

---

ngrinder-frontend/src/js/components/perftest/list/List.vue

- change to aware use time zone
- it have been checked the day equality based on UTC zone

Fix today highlight to aware user time zone

---

ngrinder-frontend/src/js/components/perftest/list/List.vue
ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue
ngrinder-frontend/src/js/components/perftest/list/mixin/TableConfig.vue

- Add label "No Data" when data is empty

Add label when the small chart data is empty

---

ngrinder-controller/src/main/java/org/ngrinder/infra/config/DynamicCacheConfig.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyMavenProjectScriptHandler.java
ngrinder-controller/src/main/java/org/ngrinder/script/model/GitHubConfig.java
ngrinder-controller/src/main/java/org/ngrinder/script/service/GitHubFileEntryService.java
ngrinder-core/src/main/java/org/ngrinder/common/util/PathUtils.java

Fix bugs of github storage

---

ngrinder-frontend/src/js/components/perftest/detail/Detail.vue

Make test status change correctly.

Make test status change correctly

---

ngrinder-frontend/src/js/components/script/Editor.vue

1. Add editor link to validation result. when clicked that, focus moves to the corresponding line in the editor.

Add editor link to validation result

---

ngrinder-controller/src/main/resources/messages_cn.properties
ngrinder-controller/src/main/resources/messages_en.properties
ngrinder-controller/src/main/resources/messages_kr.properties
ngrinder-frontend/package.json
ngrinder-frontend/src/js/components/perftest/detail/Detail.vue
ngrinder-frontend/src/js/main.js

1. Add button for return to list.

Add return to list button

---

ngrinder-controller/src/main/java/org/ngrinder/script/service/ScriptValidationService.java

Fix log replacement to hide home path correctly.

Fix log replacement to hide home path correctly

---

ngrinder-frontend/src/js/components/perftest/detail/Config.vue

Place add host button at top of the window

Place add host button at top of the window

---

ngrinder-frontend/package.json
ngrinder-frontend/src/js/main.js
ngrinder-frontend/src/js/vue-router-referer.js

Remove`vue-router-referer` module.

Remove vue-router-referer

---

ngrinder-frontend/src/html/app.html
ngrinder-frontend/src/js/components/Base.vue
ngrinder-frontend/src/js/components/common/Copyright.vue

1. Adjust main page layout.
2. Hide default browser scroll.
- Before
- After

Beautify css

---

ngrinder-frontend/src/js/components/script/Editor.vue

Add return to list button to script editor.

Add return to list button to script editor

---

ngrinder-groovy/src/main/java/net/grinder/scriptengine/groovy/GroovyScriptEngineService.java
ngrinder-groovy/src/test/java/net/grinder/scriptengine/groovy/GrinderRunnerTest.java
ngrinder-groovy/src/test/java/net/grinder/scriptengine/groovy/GroovyScriptEngineTest.java

Update code license

---

ngrinder-controller/src/main/resources/messages_cn.properties
ngrinder-controller/src/main/resources/messages_en.properties
ngrinder-controller/src/main/resources/messages_kr.properties
ngrinder-frontend/src/js/components/script/SearchBar.vue
ngrinder-frontend/src/js/main.js

Reorder script search bar.
1. Before
2. After

Reorder script search bar

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyMavenProjectScriptHandler.java
ngrinder-controller/src/main/java/org/ngrinder/script/repository/GitHubFileEntryRepository.java
ngrinder-controller/src/main/java/org/ngrinder/script/service/FileEntryService.java
ngrinder-controller/src/main/java/org/ngrinder/script/service/GitHubFileEntryService.java

After supporting GitHub storage, the groovy maven project can be in root path(`src/main/java`).
so, i make support that.

Make groovy maven scripts work on root path

---

RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
ngrinder-frontend/package.json
ngrinder-frontend/webpack.config.js

Bump version up to 3.5.0

---

ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyMavenProjectScriptHandler.java

`ClassPathResource.getFile()` is throw `FileNotFoundException` if your resources url in executable jar(`jar://` protocol).
I changed the file path to get from constant.

Fix case executable jar can't create groovy maven script

---

RELEASE-NOTE.md
ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyMavenProjectScriptHandler.java
ngrinder-frontend/src/js/components/agent/modal/AddConnectionAgentModal.vue

Release 3.5.0

---

README.md

https://github.com/naver/ngrinder/tree/feature/update-readme#quick-start

Add quick start guide to readme

---

index.html

Add quick start guide to pages

---

ngrinder-frontend/src/js/components/perftest/list/SmallChart.vue

Relocate small chart legends to bottom-right to improve chart visibility

---

ngrinder-frontend/src/js/components/script/Editor.vue

Add full screen button to editor.

Add full screen button to editor

---

ngrinder-frontend/src/js/components/script/mixin/Guide.vue

```@Test ``` was missed in guide of script editor.

Add missing @Test in Guide

---

NOTICE
README.md
RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
ngrinder-frontend/package.json
ngrinder-frontend/webpack.config.js

Release 3.5.1

---

build.gradle
ngrinder-controller/build.gradle
ngrinder-groovy/build.gradle

Add additional groovy dependencies.

Add additional groovy dependencies

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentPackageService.java
ngrinder-controller/src/main/java/org/ngrinder/common/util/StringUtils.java
ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentPackageServiceTest.java
ngrinder-controller/src/test/java/org/ngrinder/common/util/StringUtilsTest.java

Before filtering, I remove the release type(-SNAPSHOT, -GA, -patch, -p1) from the dependency.

Fix agent dependencies filtering logic

---

README.md
RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
ngrinder-frontend/package.json
ngrinder-frontend/webpack.config.js

Release 3.5.1-p1

---

ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/model/Event.java

Add peftest name to webhook payload

Add peftest name to webhook payload

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/controller/PerfTestApiController.java
ngrinder-controller/src/main/resources/messages_cn.properties
ngrinder-controller/src/main/resources/messages_en.properties
ngrinder-controller/src/main/resources/messages_kr.properties
ngrinder-frontend/src/js/components/Base.vue
ngrinder-frontend/src/js/components/agent/mixin/TableConfig.vue
ngrinder-frontend/src/js/components/perftest/detail/Report.vue

1. Add button for refreshing agent logs
- To avoid expensive refresh.
2. Resize column of agent list table
- Column size of agent list table is fixed.

UI improvement

---

ngrinder-controller/src/main/java/org/ngrinder/security/DefaultLdapLoginPlugin.java

- In case search only single depth, cannot find users depends on LDAP server configuration

Change LDAP search scope to all subtrees

---

ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/controller/WebhookController.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/model/Event.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/model/WebhookActivation.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/model/WebhookConfig.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/service/NGrinderWebhookClient.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/service/WebhookConfigService.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/service/WebhookService.java
ngrinder-frontend/src/js/components/common/navigator/UserMenu.vue
ngrinder-frontend/src/js/components/settings/Settings.vue
ngrinder-frontend/src/js/components/settings/WebhookSettings.vue
ngrinder-frontend/src/js/main.js

1. Adjust layout of the  webhook settings page.
2. Add tags data to the payload.

Improve UI

---

README.md
RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_maven/pom.xml
ngrinder-frontend/package.json
ngrinder-frontend/webpack.config.js

3.5.2 RELEASE

---

ngrinder-controller/src/main/java/org/ngrinder/security/NGrinderAuthenticationProvider.java
ngrinder-controller/src/main/java/org/ngrinder/user/service/UserService.java

Fix case unintended reset of followers at login

Fix case unintended reset of followers at login

---

ngrinder-controller/src/test/java/org/ngrinder/agent/service/AgentServiceTest.java
ngrinder-controller/src/test/java/org/ngrinder/agent/service/MockAgentService.java
ngrinder-core/src/test/java/net/grinder/engine/agent/PropertyBuilderTest.java

Fix failed unit test

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java

Prevent NEP If exception is occured  before single console isn't prepared.

Prevent NEP if start console is failed

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
ngrinder-controller/src/main/java/org/ngrinder/common/util/LoggingUtils.java
ngrinder-controller/src/main/java/org/ngrinder/infra/webhook/plugin/NGrinderWebhookPlugin.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestRunnable.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/samplinglistener/MonitorCollectorPlugin.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/samplinglistener/TooManyErrorCheckPlugin.java
ngrinder-controller/src/main/java/org/ngrinder/script/handler/GroovyMavenProjectScriptHandler.java
ngrinder-controller/src/main/java/org/ngrinder/script/handler/NullScriptHandler.java
ngrinder-controller/src/main/java/org/ngrinder/script/handler/ScriptHandler.java
ngrinder-controller/src/main/java/org/ngrinder/script/service/ScriptValidationService.java
ngrinder-controller/src/test/java/org/ngrinder/common/util/LoggingUtilsTest.java
ngrinder-controller/src/test/java/org/ngrinder/perftest/service/MockPerfTestRunnable.java
ngrinder-core/src/main/java/net/grinder/SingleConsole.java
ngrinder-core/src/main/java/org/ngrinder/monitor/share/domain/MBeanClient.java

Add test id & test user information to log to make an easy searching in multi-user env.

Add identity information to perftest related log

---

build.gradle

Check property existence in bintray gradle configuration.

Check property existence in bintray gradle configuration

---

README.md
RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_gradle/build.gradle
ngrinder-frontend/package.json
ngrinder-frontend/webpack.config.js

3.5.3 Release

---

build.gradle
gradle.properties
ngrinder-controller/build.gradle
ngrinder-groovy/src/main/java/net/grinder/scriptengine/groovy/junit/GrinderRunner.java
ngrinder-runtime/build.gradle

Bump junit version up

---

ngrinder-controller/src/main/java/org/ngrinder/infra/config/TaskConfig.java
ngrinder-controller/src/main/java/org/ngrinder/perftest/service/samplinglistener/AgentDieHardListener.java
ngrinder-core/src/main/java/net/grinder/SingleConsole.java

Increase agent die-hard schedule interval from 2ms to 2s.

Increase agent die-hard schedule interval

---

docker/agent/Dockerfile
docker/controller/Dockerfile

Add UTF8 option to Dockerfile 
something to do with this #698

Add UTF8 option to Dockerfile

---

README.md

I've set up discussions in github repo.
It is better to use this for general QnA.

Add discussion link in README

---

index.html

Add discussion link

---

.github/ISSUE_TEMPLATE/bug-report.md

Add caution message to issue template

---

ngrinder-controller/build.gradle
ngrinder-controller/src/main/resources/ngrinder-sh/agent/run_agent_internal.bat
ngrinder-controller/src/main/resources/ngrinder-sh/agent/run_agent_internal.sh

Make ngrinder runtime module is always loaded first.

Make ngrinder runtime module is loaded first

---

build.gradle
ngrinder-frontend/build.gradle

Add es-check version as a build option.
If the latest version has a bug, pass a specific version to run our build task.
https://github.com/naver/ngrinder/issues/768

Add es-check version as a build option

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/service/PerfTestService.java

Prevent duplicated running performance test on one user.

Fix duplicated running test on one user

---

ngrinder-controller/src/main/java/org/ngrinder/perftest/service/ClusteredPerfTestService.java

Prevent duplicated running performance test on one user **in cluster mode.**

Fix duplicated running test on one user in cluster mode

---

ngrinder-controller/src/main/java/org/ngrinder/infra/init/DatabaseUpdater.java

Relevant issue : #690
If using H2, update `DATABASECHANGELOGLOCK` table before running liquibase changelogs.

Fix fail of auto-upgrade from 3.4.x to 3.5.x

---

ngrinder-controller/src/main/java/org/ngrinder/starter/NGrinderControllerStarter.java

Clean up code `NgrinderControllerStarter.java`

Clean up code NgrinderControllerStarter

---

ngrinder-controller/src/main/java/org/ngrinder/agent/service/AgentService.java
ngrinder-core/src/main/java/org/ngrinder/service/AbstractAgentService.java
ngrinder-core/src/main/java/org/ngrinder/service/IAgentManagerService.java

Make AgentService.getLocalAgents() to return only it's own local agents.

Make AgentService.getLocalAgents() to return only it's own local agents

---

ngrinder-frontend/src/js/components/common/Copyright.vue

Make footer have  fixed height regardless of margin.

Make footer have  fixed height

---

ngrinder-controller/src/main/resources/script_template/basic_template_groovy.ftl
ngrinder-controller/src/main/resources/script_template/legacy_template_groovy.ftl
ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPRequest.java
ngrinder-runtime/src/main/java/org/ngrinder/http/HTTPRequester.java
ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPatch.java
ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPost.java
ngrinder-runtime/src/main/java/org/ngrinder/http/method/HTTPPut.java
ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/BasicMultipartEntity.java
ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/DelegateDataStreamChannel.java
ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/FileMultipartEntity.java
ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/MultipartEntity.java
ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/MultipartEntityBuilder.java
ngrinder-runtime/src/main/java/org/ngrinder/http/multipart/MultipartEntityProducer.java

- Implement multipart form data entity that allows text and file parts.

Provides multipart form data parameter

---

README.md
RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_gradle/build.gradle
ngrinder-frontend/package.json
ngrinder-frontend/webpack.config.js

Release 3.5.5

---

README.md
RELEASE-NOTE.md
build.gradle
ngrinder-controller/src/main/resources/application.yml
ngrinder-controller/src/main/resources/script_template/groovy_gradle/build.gradle
ngrinder-frontend/package.json
ngrinder-frontend/src/js/main.js
ngrinder-frontend/webpack.config.js

Release 3.5.5-p1

---

ngrinder-controller/src/main/java/org/ngrinder/script/model/GitHubConfig.java
ngrinder-controller/src/main/java/org/ngrinder/script/service/GitHubFileEntryService.java
ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog_schema_33.xml

```
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'scm' at row 1
```
Some github scripts have too long names to save them.

Increase scm column size

---

ngrinder-controller/src/main/resources/ngrinder_datachange_logfile/db.changelog.xml

Add new changelog that added at https://github.com/naver/ngrinder/commit/25ac2bbab818a1082e62a6c5afd91eb4eb08888f

Add new changelog
